# Generated by Django 4.1.7 on 2023-03-03 14:07

import Picbed.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to=Picbed.models.user_directory_path, verbose_name='存放图片')),
                ('md5', models.CharField(max_length=128, unique=True, verbose_name='md5值')),
                ('img_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'uploadImage',
            },
        ),
    ]
