# Generated by Django 4.1.7 on 2023-03-03 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Post.category'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='uuid',
            field=models.UUIDField(),
        ),
    ]
