# Generated by Django 4.1.7 on 2023-03-03 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Post', '0004_recordlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='comment',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers_comment', to=settings.AUTH_USER_MODEL)),
                ('topic_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers_comment', to='Post.topic')),
            ],
        ),
    ]
