# Generated by Django 4.1.7 on 2023-03-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_topic_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='num_like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='uuid',
            field=models.UUIDField(default=0),
            preserve_default=False,
        ),
    ]
