# Generated by Django 4.1.7 on 2023-03-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0007_comment_num_like_comment_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='num_comment',
            field=models.IntegerField(default=0),
        ),
    ]
